import { getF32 } from "@/game/rng.js";

function makeRandomSequence(maxValue, seed, advanceFunction, ver_1_0) {
    const pArray = new Array(maxValue).fill(-maxValue);

    let slotsFilled = 0;

    while (true) {
        seed = advanceFunction(seed);

        let random = Math.floor(
            getF32(seed, ver_1_0) * (maxValue - slotsFilled),
        );

        if (maxValue > 0) {
            let j = 0;

            for (let i = 0; i < maxValue; i += 1) {
                if (pArray[j] < 0) {
                    random -= 1;

                    if (random < 0) {
                        pArray[j] += maxValue;
                        pArray[slotsFilled] += j;
                        slotsFilled += 1;

                        if (slotsFilled >= maxValue) {
                            return [pArray, seed];
                        }

                        break;
                    }
                }

                j += 1;
            }
        }
    }
}

const CALC_BEFORE_WIND = 9;
const MAX_WIND_DIR = 8;
const MAX_WIND_SPD = 16;

const HOLES = 9;

export function shouldExtraRngAdvanceOccurWhenGeneratingWind(
    seed,
    advanceFunction,
    ver_1_0,
) {
    // an extra rng advance occurs when 0 is not in the first 9 speeds generated by the wind generation function
    // this is an abridged version of it up until the point where we can check where 0 is

    for (let i = 0; i < CALC_BEFORE_WIND; i++) {
        seed = advanceFunction(seed);
    }

    let randomDirs;
    [randomDirs, seed] = makeRandomSequence(
        MAX_WIND_DIR,
        seed,
        advanceFunction,
        ver_1_0,
    );

    let randomSpeeds;
    [randomSpeeds, seed] = makeRandomSequence(
        MAX_WIND_SPD,
        seed,
        advanceFunction,
        ver_1_0,
    );

    return !randomSpeeds.slice(0, HOLES).includes(0);
}
